apiVersion: v1
kind: Service
metadata:
  name: thunder2
spec:
  type: {{ .Values.serviceType }}
  ports:
    - port: {{ .Values.serviceFrontendPort }}
      targetPort: {{ .Values.serviceBackendPort }}
  selector:
    app: thunder2
