# How many instances of Thunder to deploy
replicaCount: 1

# The version of Thunder to deploy
thunderImageTag: edge

# Required AWS access keys
awsAccessKeyId: "123456789"
awsSecretAccessKey: "123456789"

# Service and port information
serviceType: ClusterIP
serviceFrontendPort: 80
serviceBackendPort: 8080
serviceAdminPort: 8081

# Fields for config.yaml

# Database information
database:
  type: mongodb
  useLocal: true
  localUsername: superuser
  localPassword: secretpassword
  connectionString: mongodb://superuser:secretpassword@0.0.0.0:27017
  databaseName: users-db
  collectionName: users

# SES information
emailEnabled: false

# Thunder authentication
applicationKeys:
  - name: application
    secret: secret
