# Information to access DynamoDB
dynamo:
  endpoint: http://localhost:4567
  region: us-east-1
  tableName: pilot-users-test

# Information to access SES
email:
  endpoint: http://localhost:9001
  region: us-east-1
  fromAddress: noreply@sanctionco.com

# Approved Application Authentication Credentials
approvedKeys:
  - application: application
    secret: secret

# Enforce property validation
properties:
  - name: uniqueID
    type: string
  - name: attributes
    type: list

# Server configuration
server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081
