extends: google

parserOptions:
  sourceType: "module"
  ecmaVersion: 11

rules:
  # Never allow trailing commas on lists
  comma-dangle:
    - error
    - never
  # Align based on key values
  key-spacing:
    - error
    - align: value
  # Max line length should be 120
  max-len:
    - error
    - code: 120
  # Allow multiple spaces when declaring requires
  no-multi-spaces:
    - error
    - exceptions:
        VariableDeclarator: true
  # Always force spacing between curly braces
  object-curly-spacing:
    - error
    - always
  # Do not require JSDoc
  require-jsdoc:
    - off
  valid-jsdoc:
    - off
