extends: google

parserOptions:
  ecmaVersion: 6

rules:
  comma-dangle:
    - error
    - never
  key-spacing:
    - error
    - align: value
  max-len:
    - error
    - code: 100
  no-multi-spaces:
    - error
    - exceptions:
        VariableDeclarator: true
  object-curly-spacing:
    - error
    - always
  valid-jsdoc:
    - error
    - requireReturn: false
      requireReturnType: false

