name: Approve Dependabot

on:
  pull_request_target

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request_target' && github.actor == 'dependabot[bot]'

    steps:
      - name: Auto approve
        uses: hmarr/auto-approve-action@v2.1.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
