name: Automerge Dependabot PR

on:
  pull_request_target:
    branches: [ master ]

jobs:
  automerge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    
    permissions:
      pull-requests: write

    steps:
      - name: Enable Automerge
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Approve
        uses: hmarr/auto-approve-action@v3.0.0
