name: Sync Requirements File

on:
  push:
    branches: [master]
    paths:
      - "docs/Pipfile"
  schedule:
  - cron: "0 12 * * 2"

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.4.0

      - name: Setup Python
        uses: actions/setup-python@v2.3.1
        with:
          python-version: '3.x'

      - name: Sync Python dependencies
        run: |
          cd docs/
          python sync-requirements-file.py

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3.12.0
        with:
          branch: github-actions/sync-requirements-file
          title: Upgrade sphinxcontrib-httpexample in readthedocs-requirements file
          body: Upgrade sphinxcontrib-httpexample in readthedocs-requirements file
          commit-message: Sync readthedocs-requirements file
          labels: "Type: Dependencies,Size: Small"
